# numpy

For a more comprehensive introduction to NumPy, see the official tutorial here:  [https://docs.scipy.org/doc/numpy-dev/user/quickstart.html](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html).

The main object in NumPy is the multidimensional array.  In NumPy, dimensions are called *axes*.  The **```numpy.array()```** function is how you can create a simple array.  Note that two parentheses that are needed **```(())```** for correct syntax:

In [1]:
import numpy

# special code for Jupyter Notebook; allows in-line plotting (may not be needed on your machine)
%matplotlib inline

In [2]:
array1 = numpy.array(( [1,2,3], [4,5,6], [7,8,9] ))
array2 = numpy.array([ (1,2), (3,4) ]) # brackets and parentheses both work
array3 = numpy.array(( (1,2), (3,4) ))
array4 = numpy.array(( 'apple', 'orange', 'banana' ))

__ERRORS IN PYTHON:__
* Usually a line number is given.  Toggle lines on/off in the a notebook by typing:   ```esc``` and then ```shift```+```L```
* Here, it says ```invalid syntax```, so we've done something wrong... __can you fix it?__

In [3]:
print(array1) # print function requires () in Python 3.x
print() # print empty line for separator
print(array1.shape)
print()
print(array2)
print()
print(array3
print()
print(array4)

SyntaxError: invalid syntax (<ipython-input-3-ed729f202d23>, line 8)

In [4]:
print("I had an " + array4[0] + " with lunch.") # note the print statement accepts a + to concatenate strings

I had an apple with lunch.


## numpy array copying versus assigning

In [5]:
array5 = array3
print(array5)

[[1 2]
 [3 4]]


In [6]:
array5 *= 2 # multiply array5 by 2, in place
print(array5)

[[2 4]
 [6 8]]


In [7]:
print(array3) # note array3 is the SAME as array5, and changes accordingly

[[2 4]
 [6 8]]


In [8]:
# avoid this behavhior by using numpy.copy
array5 = numpy.copy(array3)
array5 *= 2
print(array5)
print(array3)

[[ 4  8]
 [12 16]]
[[2 4]
 [6 8]]


### Placeholder arrays:  zeros, ones, and empty

You can create a large placeholder array to fill in later.  This can be done using **```numpy.zeros()```**, **```numpy.ones()```**, or **```numpy.empty()```**:

In [9]:
zeros_array = numpy.zeros((5,5)) # (nrows,ncols)
ones_array = numpy.ones((5,5))
empty_array = numpy.empty((3,3))

In [10]:
print(empty_array)

[[2.68156159e+154 1.29074163e-231 2.47032823e-323]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


# Data types

* The default data type for a float in numpy is **```numpy.float64```**
* The default data type for a numpy array is a **```numpy.ndarray```**
* You can check this using the **```type()```** function

In [11]:
print(type(zeros_array[0,0]))

<class 'numpy.float64'>


The ```.mean()``` and ```.shape()``` syntax are methods that belong to ```array1```:

In [12]:
print(array1.shape) # same as numpy.shape(array1)
print(array1.mean()) # same as numpy.mean(array1)

(3, 3)
5.0


## The ```numpy.arange()``` and ```numpy.linspace``` functions

**```numpy.arange()```** is analogous to **```range()```**, except **```numpy.arange()```** outputs a ```numpy.ndarray``` object, and **```range()```** outputs an iterator.

* To see the documentation for any of these functions, google them... NumPy and SciPy functions are all very well documented.  For example:  http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.arange.html

* You can also use the ```?numpy.arange``` or ```??numpy.arange``` syntax in Jupyter Notebook

In [13]:
numpy.arange(10) # if you enter an integer, it will be of numpy.int data type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
numpy.arange(10.) # adding the decimal ensures it is of numpy.float type

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

**```numpy.linspace(start, stop, N)```** generates an array of **```N```** evenly spaced numbers from start to stop.

In [15]:
numpy.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Operations on arrays

Basic arithmetic operations on NumPy arrays occur *elementwise*.  

In [16]:
A = numpy.array(( [1,2], [3,4], [5,6] ), dtype=float)
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [17]:
B = numpy.array(( [7,8], [9,10], [11,12] ))
print(B)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [18]:
print(A+B)
print(A-B)

[[ 8. 10.]
 [12. 14.]
 [16. 18.]]
[[-6. -6.]
 [-6. -6.]
 [-6. -6.]]


In [19]:
print(A*B) # element-wise mutiplication

[[ 7. 16.]
 [27. 40.]
 [55. 72.]]


### Dot products on arrays

A dot product of two arrays needs to have matching interior dimensions: ```[i x j] . [j x k] = [j x k]```

__Can you solve the error below?  Hint:  Transpose an array in place using ```array_name.T``` or ```numpy.transpose(array_name)```__

In [20]:
print(A.shape)
print(B.shape)
print(numpy.dot(A,B)) # matrix dot product

(3, 2)
(3, 2)


ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

Quick computations of means, sums, min, and max can be computed using either the **```A.function()```** or the **```numpy.function(A)```** notation:

In [21]:
print(A.mean(), \
      A.sum(), \
      A.min(), \
      A.max())
print(numpy.mean(A), \
      numpy.sum(A), \
      numpy.min(A), \
      numpy.max(A))

3.5 21.0 1.0 6.0
3.5 21.0 1.0 6.0


### Indexing, slicing, iterating

To index a NumPy array, use square brackets **```[i,j]```** for **```[row,column]```**.

(Don't forget zero indexing.)

In [22]:
C = numpy.arange(100).reshape((10,10)) # note array is reshaped upon creation
C[0,0]

0

In [23]:
C[:2,:3] # prints first 2 rows and 3 columns
#C[0:2,0:3] # does the same

array([[ 0,  1,  2],
       [10, 11, 12]])

In [24]:
D = numpy.arange(20)
print(D)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reverse arrays using the **```[::-1]```** syntax:

In [25]:
D[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

Skip every nth element sing the **```[::N]```** syntax

In [26]:
D[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

To print every nth element:

In [27]:
D[0:16:3] # prints first 16 elements, skips by 3

array([ 0,  3,  6,  9, 12, 15])

### Reshaping versus resizing

The **```numpy.reshape()```** function returns a *new* argument with the specified shape.
The **```numpy.resize()```** function resizes the array *in place*.

Be aware of this difference when flattening or reshaping arrays.

In [28]:
F = numpy.linspace(0,10,50)
F.shape

(50,)

In [29]:
F.reshape(10,5)

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

In [30]:
F.shape # F has not been rewritten!  Shape is still (50,)

(50,)

In [31]:
F.resize(10,5)
print(F)

[[ 0.          0.20408163  0.40816327  0.6122449   0.81632653]
 [ 1.02040816  1.2244898   1.42857143  1.63265306  1.83673469]
 [ 2.04081633  2.24489796  2.44897959  2.65306122  2.85714286]
 [ 3.06122449  3.26530612  3.46938776  3.67346939  3.87755102]
 [ 4.08163265  4.28571429  4.48979592  4.69387755  4.89795918]
 [ 5.10204082  5.30612245  5.51020408  5.71428571  5.91836735]
 [ 6.12244898  6.32653061  6.53061224  6.73469388  6.93877551]
 [ 7.14285714  7.34693878  7.55102041  7.75510204  7.95918367]
 [ 8.16326531  8.36734694  8.57142857  8.7755102   8.97959184]
 [ 9.18367347  9.3877551   9.59183673  9.79591837 10.        ]]


In [32]:
print(F.shape)
print(F.size)

(10, 5)
50
